@startuml
'https://plantuml.com/object-diagram

object 电池信息
电池信息 : 电池编号
电池信息 : 电池产品信息
电池信息 : 状态
电池信息 : 流转记录


object 流转记录
流转记录 : address
流转记录 : 状态
流转记录 : 时间戳
流转记录 : 备注

电池信息 "1 " ..> "n " 流转记录

object 企业信息
企业信息 : address
企业信息 : 企业编号
企业信息 : 企业名称
企业信息 : 统一社会信用代码
企业信息 : 电话
企业信息 : 邮箱
企业信息 : 法定代表人
企业信息 : 地址


'object 积分

'object 积分交易

@enduml
