server:
  port: 8090

spring:
  application:
    name: b-recycle
#  cloud:
#    config:
#      discovery:
#        service-id: eureka-config
#        enabled: false
#      fail-fast: true
#      profile: ${spring.profiles.active}
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brecycle?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      # 下划线转驼峰命名
      column-underline: true
  # mapper xml扫描地址
  mapper-locations: classpath*:mapper/*.xml

fisco:
  cryptoMaterial:
    certPath: "conf"
    caCert: "conf/ca.crt"
    sslCert: "conf/sdk.crt"
    sslKey: "conf/sdk.key"
#   enSslCert: "conf/gm/gmensdk.crt"
#   enSslKey: "conf/gm/gmensdk.key"

  network:
    peers:
    - "192.168.111.128:20201"
    - "192.168.111.128:20200"

# 信使功能
  amop:
#  - publicKeys: [ "conf/amop/consumer_public_key_1.pem" ]
#    topicName: "PrivateTopic1"
#  - password: "123456"
#    privateKey: "conf/amop/consumer_private_key.p12"
#    topicName: "PrivateTopic2"

# 账户相关
  account:
    keyStoreDir: "account"
  #  accountFilePath: "conf"
  # pem为明文存储
    accountFileFormat: "pem"
#  accountAddress: "0x"
# p12格式存储所需的口令
#  password: ""

# 线程池配置
  threadPool:
    channelProcessorThreadSize: "16"
    receiptProcessorThreadSize: "16"
    maxBlockingQueueSize: "102400"

# 合约地址，先由WeBASE部署后在修改该处
contract-addr:
  helloworld: "0xc53b11e5a30a5dccff4322203dcccf3b5532a538"
