@startuml
'https://plantuml.com/class-diagram

'电池溯源模块
class Battery {
电池信息
溯源记录
+ 查询溯源记录()
+ 电池状态变更()
}
note left of Battery
电池合约
1. 电池状态变更需要根据不同状态
   进行权限判断
end note

class BatteryFactory {
电池列表
电池当前所有者

+ 新增电池()
+ 根据id查找电池()
+ 根据id修改电池状态()
+ 根据批次号查找电池()
+ 根据批次号修改电池状态()
+ 查询当前地址拥有的电池()
}
note left of BatteryFactory
电池工厂合约
end note

Battery --> BatteryFactory


'机构准入模块
class Enterprise {
address
企业名称
统一社会信用代码
电话
邮箱
法定代表人
地址
备注
}
note left of Enterprise
企业信息
end note

class EntAccess {
已准入的企业列表
机构类型与企业id映射
企业id与机构类型映射

+ 企业准入()
+ 企业信息变更()
+ 根据企业id查找对应机构类型()
+ 根据机构类型查找对应企业()
}
note left of EntAccess
企业准入合约
1. 企业信息变更需要特定权限
end note

Enterprise --> EntAccess

@enduml