@startuml
'https://plantuml.com/object-diagram

object 电池信息
电池信息 : 电池编号
电池信息 : 电池产品信息
电池信息 : 状态
电池信息 : 流转记录

object 流转记录
流转记录 : address
流转记录 : 状态
流转记录 : 时间戳
流转记录 : 备注

object 电池工厂
电池工厂 : 电池列表
电池工厂 : 电池所有者映射关系

电池信息 "1 " <..> "n " 流转记录
电池工厂 "1 " <..> "n " 电池信息

object 企业信息
企业信息 : address
企业信息 : 企业编号
企业信息 : 企业名称
企业信息 : 统一社会信用代码
企业信息 : 电话
企业信息 : 邮箱
企业信息 : 法定代表人
企业信息 : 地址
企业信息 : 备注

object 企业类别
企业类别 : 企业分类映射
企业类别 : 已准入的企业列表

企业类别 "n " <..> "n " 企业信息

'object 积分

'object 积分交易

@enduml
